### PR TITLE
Add images for weave 2.8.1

### PR DESCRIPTION
**Pull request by SamLR**
As the image may be accessed by either gitsha or release version

### CODE REVIEW

**Review by ozamosi — APPROVED** [review]

**Comment by bridgegh** [comment]
Is this grafana one of our images which is still coming up in the flux agent logs:
rate limited: rate: Wait(n=1) would exceed context deadline" ref=docker.io/grafana/grafana:master-565387a42e5e450d723c4522665f71f6a4d3589e-new-pipeline

**Comment by bridgegh** [comment]
Also can the helm operator image be moved to ghcr? Its coming up in the weave cloud flux agent logs.
rate limited: rate: Wait(n=1) would exceed context deadline" ref=docker.io/fluxcd/helm-operator:0.9.0

**Comment by SamLR** [comment]
> Is this grafana being pulled form docker one of our images which is still coming up in the flux agent logs: rate limited: rate: Wait(n=1) would exceed context deadline" ref=docker.io/grafana/grafana:master-565387a42e5e450d723c4522665f71f6a4d3589e-new-pipeline

@bridgegh As far as I know that's not one of our images. 

> Also can the helm operator image be moved to ghcr? Its coming up in the weave cloud flux agent logs.
rate limited: rate: Wait(n=1) would exceed context deadline" ref=docker.io/fluxcd/helm-operator:0.9.0

I think this needs to be arranged with the flux team as this image isn't installed by launcher.

**Comment by bridgegh** [comment]
Isn't "docker.io/grafana/grafana:master" included with Prometheus that we maintain for weave cloud? Prometheus is being hosted in quay.io but not grafana?  "for the prometheus images (prometheus, node-exporter, cloudwatch-exporter) we'll use the copies in quay.io"

**Comment by SamLR** [comment]
The prometheus, node-exporter and cloudwatch-exporter images are all installed by the launch generator. I'm not sure how grafana is being installed but it's not via a process that we control (as far as I know).

**Comment by ozamosi** [comment]
@SamLR is right - there's no grafana in weave cloud.

What they didn't mention is that this is a merged PR that relates to weave net's images. As long as your questions aren't related to that, please refrain from posting them here.

**Pull request merged**
