### PR TITLE
Test multiple versions of k8s

### LINKED ISSUE #288: Update integration tests to consider new / multiple version of k8s
Right now it:

- Installs minikube and runs wc-launcher install / upgrade etc.
  - Locked to Kubernetes 1.9.4:
    https://github.com/weaveworks/launcher/blob/master/.circleci/config.yml#L99

- Which version of k8s does which minikube run?
  - The default is upgraded from time to time w/ each minikube release e.g:
    - https://github.com/kubernetes/minikube/pull/4444/files
  - You can specify the version on minikube start:
`--kubernetes-version string    The kubernetes version that the minikube VM will use (ex: v1.2.3) (default "v1.14.3")`

We should continue testing 1.9 as many customers use it. Additionally we should test `latest` and maybe another in between.

### PR DESCRIPTION
**Pull request by foot**
- First go, use even more yaml anchor helpers

Fixes #288

### CODE REVIEW

**Comment by foot** [comment]
> I've been toying with the idea of generating travis/circle CI files from js/ts and jk to go beyond anchors, but it seems anchors can be made quite readable :)

Yes! That was plan B when anchors obviously failed, but they worked okay in the end.

**Comment by rade** [comment]
This is awesome!

Two niggles
- missing trailing newline
- it would have been good to squash some of the commits, to elide missteps

**Comment by foot** [comment]
> missing trailing newline

Will fix

> it would have been good to squash some of the commits, to elide missteps

I tested out the "squash and merge" feature of GitHub for the first time which has made a history that looks like this now:

```
* baf30e1 (HEAD -> master, origin/master, origin/HEAD) Test multiple versions of k8s (#291)
| * 50102a4 (origin/288-update-integration-tests-to, 288-update-integration-tests-to) Re-run kubernetes jobs once a day in case of new k8s
| * 7c6f178 Getting bash syntax in order
| * ca03827 Add a third "stable" target for k8s testing
| * 5e9a2d7 Factor out some more things
| * c54a33b even edgeier?
| * f57578b no dice, newer machine image
| * 122583d Internet suggested hack to get minikube+circleci
| * 6c545c0 Test earlier minikube
| * 0f2c5f6 Ooops, wrong syntax, disable some jobs for now
| * 81439ba Test multiple versions of k8s
|/
*   e51f65d Merge pull request #289 from weaveworks/fixes-minikube-dns-failures
```

E.g. It created a new squashed commit on master rather than a merge commit. I'll avoid that in the future as its a bit confusing.

**Comment by rade** [comment]
I would stay away from "squash and merge" and be more selective. Squashing all commits into one is rarely the right level of granularity.

**Pull request merged**
